### PR TITLE
Added option to create .Rproj file based on user selection of R language

### PR DESCRIPTION
**Pull request by jibarozzo**
This update introduces a new .Rproj environment with default settings. Additionally, Git is initialized for version control, all using usethis::create_project() and usethis::use_git() functions.

# Changes

1. New Project Environment:

- The project environment is created using usethis::create_project(), ensuring the .Rproj file is properly configured for RStudio workflows.

2. Git Initialization:

- Git is set up using usethis::use_git(), enabling version control right from the start.

3. Directory Cleanup:

- After project creation, the /R subdirectory is removed to avoid conflicts with the existing /src directory structure, as the source files are managed separately.

# Caveat

- If creating in a directory that already has Git initialized it will not create .Rproj file
- *This need further thought and debugging!*

# Next Steps

- Navigate into the newly created directory, confirm that all configurations are properly set up, and begin using Git for version tracking.

### CODE REVIEW

**Comment by SaintRod** [comment]
@jibarozzo I'll take a look soon. Thanks for taking the time to submit a PR!

**Comment by jibarozzo** [comment]
> @jibarozzo I'll take a look soon. Thanks for taking the time to submit a PR!

Thank you for sharing this neat script! It takes out a lot of the guess work for me. :)

**Comment by SaintRod** [comment]
I've been mulling this over. I like the idea but I *feel* it's out of scope.

As-is, no language-specific artifacts or infrastructure are created.
Everything except the testing dir is language agnostic.
If `-l r` is specified then you decide to switch to Pyhon there's no difference.
Switching from Py/R to Jullia requires renaming the testing dir, which is a minor inconvenience.

My last thought is about installing things in the base environment.
Both Py and Julia recommend against doing so.
Now, I know that `renv` isn't part of the standard library so it must be installed in the base environment, but all other libraries should be installed using `renv::install`.

Thoughts @jibarozzo ?

**Comment by jibarozzo** [comment]
I see. After thinking about it, this change could be an inconvenience if they decide to switch language or if they are creating Shiny apps or packages which requires a slightly different setup. My projects tend to be R based so I know what I need from the get go.  I wish R was shipped with `renv` to avoid messing with the base environment. 
Another way of doing it while still keeping the agnostic spirit is to make it a flag of its own and have the user specify they need a project. An `.Rproj` file can be created in the script itself with some defaults, something like this (I haven't worked out all the kinks): 
```
Rproj="Version: 1.0

RestoreWorkspace: No
SaveWorkspace: No
AlwaysSaveHistory: Default

EnableCodeIndexing: Yes
UseSpacesForTab: Yes
NumSpacesForTab: 4
Encoding: UTF-8

RnwWeave: knitr
LaTeX: XeLaTeX

AutoAppendNewline: Yes
StripTrailingWhitespace: Yes
LineEndingConversion: Posix"

if [ "$env"=="rproj" ]; then
  echo "$Rproj" > $path/$path.Rproj
fi
```
```
$ ./create-project.sh -l r -v rproj -p r_project_test
```

This would just give them a text file they can delete if needed, but nothing in the base environment has been altered. 

What do you think @SaintRod ?

**Comment by SaintRod** [comment]
I've created a new branch called dev so we can work on these ideas.
@jibarozzo please submit a new PR to that branch.

I like the text file idea, but the kinks should be addressed.

Also, maybe it's not a bad idea to install renv in the base environment.
It would be a nudge to use project environments.

So, when `-l r`:

- Run R code to a) test if renv is installed otherwise install it and b) run `renv::int()`
- Create the text file or since the project uses renv now, we can install usethis and leverage the previous ideas, i.e., `usethis::create_project`

**Comment by jibarozzo** [comment]
Will do.

**Comment by SaintRod** [comment]
Closed as moving work to dev branch

**Pull request closed without merging**
